# Generated by Django 4.1.7 on 2023-02-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lift", "0002_lift_busy"),
    ]

    operations = [
        migrations.AddField(
            model_name="lift",
            name="is_OOO",
            field=models.BooleanField(default=False),
        ),
    ]
