# Generated by Django 4.1.7 on 2023-02-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lift", "0005_rename_lift_id_requests_per_lift_lift"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requests_per_lift",
            name="called_on_floor",
        ),
        migrations.AddField(
            model_name="requests_per_lift",
            name="history",
            field=models.CharField(default="called", max_length=200),
        ),
    ]
