name: Django test

on:
  pull_request:
    branches: [main, add_drf]

jobs:
  simple_test:
    runs-on: Ubuntu-latest
    steps:
      - name: setup
        uses: actions/checkout@v2
      - name: setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: run tests
        run: |
          python manage.py test
